### ISSUE TITLE
version

### ISSUE THREAD

**Issue by tiryaki92** [arafey/openevic#1]
Hi arafey. This is great work. After that you will often update the application. ClockSelect is not updating anymore

**Comment by arafey** [comment]
I will try to update it as often as possible since I have many features planned. Hopefully, at least every week.

**Comment by tiryaki92** [comment]
Arafey , Do you want me to give you an idea about the feature

**Comment by arafey** [comment]
Sure, but add it as a new issue. If you have more than one idea, please put each idea in a separate issue. Thanks.
