### ISSUE TITLE
Add to fire button lock

### ISSUE THREAD

**Issue by tiryaki92** [arafey/openevic#11]
Sometimes we do not turn off the device and it stops in our pockets. It would be nice to lock the 2 clickle firing key for this. You can add lock fire to the clicks menu options for this. Alternatively, the firing key can be locked with the + and - keys when + and - are pressed together.

**Comment by tiryaki92** [comment]
i have a new idea. I saw it on a smok device. These keys are locked when the + and - keys are pressed for 1/5 of a second. In addition, you can lock the fire key. This would be very useful.

**Comment by arafey** [comment]
I'm trying to understand this issue. Do you want to be able to fire without holding down the fire button?

**Comment by tiryaki92** [comment]
No. I want to lock all the keys with the fire button when the + and - keys are the same and pressed briefly.

**Comment by arafey** [comment]
Why do you need a lock when you can click 5 times to turn it off?

**Comment by tiryaki92** [comment]
Because it will be more practical to lock the keys by pressing the plus and minus keys for 1/5 second.

**Comment by tiryaki92** [comment]
These keys are locked when the plus and minus keys are already pressed. Only the duration of this will be reduced and the fire button will be added to these keys. If you think it will not be good, you might not add it.

**Comment by arafey** [comment]
I think I understand now. I didn't realize that the fire button doesn't get locked when you hold +/- (I don't use the lock myself very often). I can shorten the duration to .2 s and also add the fire button to the lock.

**Comment by skorpyx** [comment]
Good idea. Mod still turns in a pocket... Turning them off is impractical.

**Comment by lojpek** [comment]
Lock is for locking + and - for not changing settings  (wattage, temperature) accidentally in your pocket. It's not for lock all buttons. Your issue is not an issue. Maybe good thing is to add in options lock +,- value for locking only +,- and locking all buttons.  For your impractical 5 click change it to 2 click ;) and you will be happy.

**Comment by arafey** [comment]
This makes sense. Holding down +/- is just as convenient as a double click to power off.

If this is really critical, send a pull request with a menu option for "all buttons locked", and I'll merge it.
