### ISSUE TITLE
Bugs and opening logo

### ISSUE THREAD

**Issue by tiryaki92** [arafey/openevic#17]
The error persists. There is no problem in trying Usa dragon's file but there is a problem in Openevic. And add that you can set the opening logon to on or off. Not so convenient

**Comment by Hansson0728** [comment]
If you set logo to off and placent top, the logo goes away, at least it did for me

**Comment by tiryaki92** [comment]
It would have been nice if the opening and closing options were available for the boot logo

**Comment by arafey** [comment]
I'll try to fix this for the next pre-release.

**Comment by tiryaki92** [comment]
thanks arafey. Will you add on and off for the opening logo?

**Comment by arafey** [comment]
I will do that also. But the weak battery error is more important.

**Comment by tiryaki92** [comment]
you are right my friend

**Comment by arafey** [comment]
Just noticed this, you can make the opening logo disappear by clicking the fire button 6 times when you turn on. Also, it doesn't prevent you from firing. You can fire while the logo is on the screen.

**Comment by tiryaki92** [comment]
This can also be applied. In the future you will turn the menu on / off for the opening logo. It's not hard for you
