### ISSUE TITLE
Evic primo crash?

### ISSUE THREAD

**Issue by skorpyx** [arafey/openevic#19]
Hello, I installed openevic 0.15 on my Evic Primo(1). On the Primo shown logo (OEV openevic 0.15) 
The device does not respond, you can not connect to a computer (NFE Toolbox, Joytech firmware update)
the computer beeps but the device was not found. Any idea to solve?

**Comment by arafey** [comment]
The Evic Primo has very little support right now. I simply  merged the basic support @rekcah5 added as a basis for future support. 

The only help I can offer is to direct you to [try this](http://www.customvapefirmware.com/fix-a-bricked-evic-vtc).

Unfortunately, I don't own a Primo to walk you through recovery but maybe @rekcah5 or someone with a Primo can chime in.

**Comment by arafey** [comment]
Also, for future warning, the commit that provides support from rekcah5/myevic@36f85a176067af3c98112ba3ec3fa3e8e089e5c4 says "Primo Hardware Compatibility (partial - firing/charging broken, don't use!"

**Comment by skorpyx** [comment]
Solved!
1, Remove battery and Tank from mod
2, while holding - and insert battery from mod 
Evic primo should boot!
I hope it will be helpful

**Comment by arafey** [comment]
Thank you, I'm glad you fixed it. When some of the more immediate issues are solved, I will try to work on better Primo support. It's probably not a good idea to try this firmware until then, unfortunately.
