### ISSUE TITLE
Add power curve presets

### ISSUE THREAD

**Issue by tiryaki92** [arafey/openevic#2]
It will be more functional if you can add soft, hard, very hard curve modes.

**Comment by tiryaki92** [comment]
i mean this
![687474703a2f2f692e696d6775722e636f6d2f434e7a6e3776512e706e67](https://cloud.githubusercontent.com/assets/26493379/24447756/b401294a-147a-11e7-9a26-aa58f22ca76c.png)

**Comment by arafey** [comment]
Depending on how curves are implemented in the code, it can be very simple or very annoying. I'll update when I find out.

**Comment by tiryaki92** [comment]
This is a screenshot from ArcticFox. Maybe you can learn from them

**Comment by arafey** [comment]
Their firmware is very good but unfortunately [it's not open source](https://github.com/maelstrom2001/ArcticFox/issues/83).

**Comment by tiryaki92** [comment]
I understand that maybe this can be difficult. You can leave it forward

**Comment by arafey** [comment]
It's still a good idea, so I'll leave it open. I want to add this but I'll get some of the less difficult ones out of the way first.

**Comment by tiryaki92** [comment]
okay. i wait Constantly updating. Good luck
