### ISSUE TITLE
Mod Frozen at splash screen after installing new firmware.

### ISSUE THREAD

**Issue by Tolga83** [arafey/openevic#23]
I just upload your latest firmware to mw wismec 2/3. Screen is freezed and only splash screen seen. (OEV openevic 0.15 )  I can not use my mod with your latest firmware. How can I fix this??

Box Model: Wismec Rx2/3

**Coil setup:**

**Comment by arafey** [comment]
Did you see #22?

**Comment by Tolga83** [comment]
Does not look the same problem (I can not come to the temperature section because you know my mod frost at the boot screen) but thank you I will wait for your next release than.

**Comment by arafey** [comment]
I created a special build for Wismec RX 2/3. I just uploaded it to releases a few minutes ago. [Here's the link.](https://github.com/arafey/openevic/releases/download/v0.15/openevic-v0-15-oldflags.bin)

**Comment by Tolga83** [comment]
I downloaded it (openevic-v0-15-oldflags.bin) and installed. Now it works fine with my Rx2/3 no crashes nor freezes happened yet. 
Thank you.

**Comment by arafey** [comment]
I'm glad to hear that it worked. It's the same fix as #22, but thank you for reporting the problem.
