### ISSUE TITLE
Did I just brick my RX 2/3?

### ISSUE THREAD

**Issue by mumpen** [arafey/openevic#24]
Help!

I just flashed the optimized .bin to my RX 2/3 and now it's just stuck on the logo screen. 
Tried every button, pulled the batteries out and put them back in, always stuck on the logo.
The biggest problem: My PC doesn't detect the mod anymore! I can't even flash another firmware...

I'm losing all hope here, can anyone help?

**Comment by tiryaki92** [comment]
Troubleshooting

This is a relatively safe update process with a low risk of hard bricking your device. The vast majority of update failures are remedied by simply retrying the upgrade procedure.

If a blank screen appears while upgrading, please restart the upgrade or press “-” button to start over.
If the updater hangs while upgrading, please try taking out the cell and atomizer first and then start the upgrade process.
Backup Upgrade/Restore Method

Connect the USB cable to your PC first and start the updater.
Hold the “+” button (the bottom right button) and then insert the USB cable into the device.
Start the upgrade as you would normally.

And Read it well. https://github.com/arafey/openevic/releases/tag/v0.15

**Comment by mumpen** [comment]
Thank you so much for that quick and helpful response!
Tried the "+" button thing and it solved everything.

Thanks and have a nice day!

**Comment by tiryaki92** [comment]
Try installing logo with fw updater in openevic main menu

**Comment by arafey** [comment]
Thank you @tiryaki92. 

@mumpen: The release notes, which you should have read, started with these two statements: 

> Due to issue #22, this release has been split into two versions: "optimized" and "generic". If you are using a Wismec Reuleaux RX2/3, please use openevic-v0-15-generic.bin.

**Comment by arafey** [comment]
Read issue #19, either the procedure I suggested there or the solution the user used to fix his/her device may help you.
