### ISSUE TITLE
boot stuck / battery measure

### ISSUE THREAD

**Issue by pipes1213** [arafey/openevic#26]
First of all, sorry for my bad English

wismec Rx2/3 -- 2 battery mode
The problem occurs with tank and without tank

I have a problem when turning on the mod, it remains booting, but I press a key and then I connect the batteries. Works

The other problem is with the voltage measurement on the batteries, I take a multimeter and I measured each one (4.125, 4.13) then I put them in the mod and it shows me (4.08, 4.20)

**Comment by arafey** [comment]
Are you using the optimized or generic version? Does this problem occur on myevic as well?

**Comment by pipes1213** [comment]
the first problem got solve with generic version but same for the batt

**Comment by arafey** [comment]
This is because optimized is not compatible with RX2/3 (see issue #22). 

Do you have the battery problem in myevic firmware?

**Comment by pipes1213** [comment]
yes,It seems like
but i found a fix
For the battery problem I went to bvo and set the offset its bounces a like bit but its ok ( close enough)

**Comment by arafey** [comment]
Perfect. I'm glad that battery voltage offset solved the problem. If you have any further issues relating to this problem, feel free to reopen this issue.
