### ISSUE TITLE
Add info tab to menu

### ISSUE THREAD

**Issue by tiryaki92** [arafey/openevic#3]
You can add an information sheet about the mode, such as total number of shots, battery life, amount of liquid consumed. There may be information tab under the expert tab on the menu

**Comment by arafey** [comment]
I was thinking of adding a "Stats" or "Info" tab in the main menu. I can probably fit all of this information on that page.

I should be able to easily add all the stats from the main screen (battery percentage, battery voltage, puff counter, puff time, real-time coil resistance, and chip temperature) into the stats/info menu.

**Comment by tiryaki92** [comment]
yes you can this.Thanks

**Comment by tiryaki92** [comment]
you are great. You do it finally. But
Why chip temperature does not exist. 
You can also add the last puff time and the last puff watt. Thank you for effort

**Comment by arafey** [comment]
Chip temperature is easy to add. 

I'll create a separate issue for last puff time and last puff power because they will require more effort and should be added to the main screen as well.

**Comment by tiryaki92** [comment]
thanks arafey

**Comment by tiryaki92** [comment]
On the info tab you can add a reset to some items by holding down the fire key. You can also add a reset to all. Thanks
