### ISSUE TITLE
RX300 

### ISSUE THREAD

**Issue by docdeath** [arafey/openevic#31]
**Box Model:RX300

**Coil setup:.25
BOTH of your firmware.s have problems .15 norm
when you add  logo causes screen to corrupt  un readable the other 15  loads and then nothing just your logo cant fire mod or any thing at all removed batts and replaced still stuck on logo reinstalled sock and fine

**Comment by arafey** [comment]
This is almost identical to the issue with the cuboid (#30). Subscribe to that issue because I will make test fixes there. I will close this one for now.
