### ISSUE TITLE
Improve battery bar for multi-battery devices

### ISSUE THREAD

**Issue by tiryaki92** [arafey/openevic#4]
You can set the third tab to show the level of both batteries

**Comment by arafey** [comment]
I've been thinking of improving the display of multi-battery voltages. The only issue is I don't have access to a multi-battery device to test it. If you have a multi-battery device and would like to test, I'll link an experimental version here once I commit it.

**Comment by tiryaki92** [comment]
This work is great.

**Comment by tiryaki92** [comment]
i have avic vtc dual. I can test it after it is built in good shape

**Comment by arafey** [comment]
That should be helpful. I will also need someone to test for devices that take 3 or 4 batteries.

**Comment by tiryaki92** [comment]
Now everybody knows that it has been updated by ClockSelect. Over time, they'll know that you've been updated. Then you will have enough device support

**Comment by fOmey** [comment]
Take a look at my fork, iv already added multi-cell voltage stats.. the bigger issue is multi-cell voltage accuracy. 

The battery voltage calculation could be done much better... Unfortunately I no longer own any compatible devices to continue developmdnt.

**Comment by arafey** [comment]
Hey, thanks for commenting. I actually have looked at your fork and merged everything up to 2aaec0ebe05c58385453ccd56c27e402312d4208, which seems to be the most recent commit in your repository. I also do not own a multi-cell device for testing multi-cell improvements.
