### ISSUE TITLE
Measured resistance is higher than actual resistance

### ISSUE THREAD

**Issue by tiryaki92** [arafey/openevic#7]
Hi thanks for this application. I used this application on two separate devices. In both, coil 0.3 reads 0.35 and above. Sometimes it even reads 0.4. This may be related to shunt resistance. Can you fix this?

**Comment by arafey** [comment]
You can change shunt resistance from the expert menu, but be careful when doing so.

I have not changed any resistance/shunt related code; do you have the same problem with myevic? Also, I assume your device is at room temperature when checking?

**Comment by tiryaki92** [comment]
Yes this is already a problem since myevic

**Comment by arafey** [comment]
What is the resistance in the default firmware?

**Comment by tiryaki92** [comment]
Normally 0.3 reads 0.28 at 0.32. 0.5 is 0.51 and 0.49. In myevic software, there is about 0.5 difference. Maybe you can fix it later.

**Comment by arafey** [comment]
Have you tried changing shunt resistance under the Expert menu?
