### ISSUE TITLE
weak battery error on multi-cell devices

### ISSUE THREAD

**Issue by tiryaki92** [arafey/openevic#9]
I updated the software to 0.12. The charge is 80 percent but I am getting a weak battery failure. it is normally firing at the strike. But I have the error.

**Comment by tiryaki92** [comment]
I pulled out the batteries and fixed the tape. But why gave this error. You'd better control it

**Comment by tiryaki92** [comment]
again error

**Comment by arafey** [comment]
What battery preset are you using? I only lowered the max current of the Samsung 30Q at this commit 6800f264510d9f24fe8d79bf31cbad36907e9608, but that was long ago. Switch your battery preset under Expert if you are using 30Q. 

If that doesn't fix it, try a previous version and see if you have the same problem.

**Comment by tiryaki92** [comment]
I am using samsung 30q. But the amps vary from 7 to 8 am. Below 15 amperes. Tomorrow I will try with vtc6 and write the result

**Comment by arafey** [comment]
Try [this build](https://github.com/arafey/openevic/files/888685/openevic.bin.zip). It's version 0.12 but with a fix for Samsung 30Q.

**Comment by tiryaki92** [comment]
Did not solve the problem. I think there is a problem with the general settings

**Comment by tiryaki92** [comment]
volt 3.24 coil 0.35. It fires normally but gives warning.

**Comment by arafey** [comment]
It's odd because I use the 30Q as well and have not had this problem yet.
I'll try to reproduce the issue on my device.

**Comment by tiryaki92** [comment]
maybe i used for dual battery

**Comment by arafey** [comment]
It's possible. Have you tried an older build like 0.11 or 0.10?

**Comment by tiryaki92** [comment]
no i will try today

**Comment by tiryaki92** [comment]
https://github.com/arafey/openevic/commit/9c2c828c2f7b1b7a0a5ef8112f9833d8f92919ab because maybe this. I have also tried version 2 now. It gives the same error in version 2

**Comment by tiryaki92** [comment]
I tested it for you.

1. No error single samsung 30Q battery
2. No error single vtc 6 battery
3. Error dual samsung 30Q battery
4. Error dual vtc 6 battery

There is an error in the multiple battery codes as you can understand from here.Thanks

**Comment by arafey** [comment]
I will fix this as soon as possible. Hopefully, in the next couple of days there will be a new version.

**Comment by arafey** [comment]
@tiryaki92, thank you for bringing this to my attention. Since I don't have any multi-cell devices, I'm relying on users for multi-cell related issues and testing.

**Comment by tiryaki92** [comment]
I would also like to inform you of some minor errors after you have uploaded all the features. Thank you

**Comment by tiryaki92** [comment]
Also the default setting in the tcr settings is joy. I think you should add the off option again. Those who want to use the original half of the device may come out

**Comment by arafey** [comment]
I just renamed "off" to "joy" because it doesn't make sense for the algorithm to be off. There is always an algorithm for TC. "Joy" makes more sense because the "off" algorithm is actually the default Joyetech algorithm.

What are the errors you want to report? If they're unrelated to "weak battery on a multi-cell device", just make new issues for them instead of posting in here.

**Comment by tiryaki92** [comment]
These are generally related issues in appearance. I will notify you after all the innovations have been done. Only one small update will take care of everything

**Comment by tiryaki92** [comment]
Did you find the source of this error

**Comment by arafey** [comment]
@USA-RedDragon and/or @fOmey, can you check 9c2c828 to see what mistake(s) I've made in that merge? I would do it myself, but I figure that since you guys have done multi-cell related code changes in myevic, it should be more obvious. Let me know if you can't/won't. Thanks.

**Comment by arafey** [comment]
If it's not there, it may be in 0e8eca70.
